export const tools = [
    { id: 'about', icon: 'user-circle', label: 'Sobre Mí', role: 'Perfil Jefe / Creativa', title: 'Diseñar es pensar, comunicar es conectar', content: 'Soy una creativa multidisciplinar enfocada en transformar ideas en experiencias visuales y estratégicas. Mi trabajo se desarrolla entre el diseño, la publicidad, el marketing y la ilustración, integrando pensamiento creativo con análisis y estrategia.', extra: 'Me interesa crear soluciones visuales con intención, que no solo se vean bien, sino que comuniquen con claridad y coherencia. Trabajo desde una perspectiva artística y estratégica.' },
    { id: 'design', icon: 'palette', label: 'Diseño Gráfico', role: 'Lenguaje Visual', desc: 'El diseño es el lenguaje visual de una marca.', manifesto: 'Desarrollo identidades visuales y piezas gráficas que reflejan la esencia de cada marca, manteniendo coherencia estética y funcional.', services: ['Identidad visual y branding', 'Diseño de marca', 'Piezas gráficas digitales e impresas', 'Sistemas visuales coherentes'] },
    { id: 'illustration', icon: 'pen-tool', label: 'Ilustración & Arte', role: 'Narrativa Visual', desc: 'La ilustración es mi espacio más libre.', manifesto: 'Exploro la ilustración como una herramienta expresiva que complementa proyectos visuales y aporta identidad, emoción y carácter.', services: ['Ilustración editorial', 'Arte conceptual', 'Elementos ilustrados para marcas', 'Exploración visual y artística'] },
    { id: 'publicity', icon: 'megaphone', label: 'Publicidad', role: 'Comunicación Estratégica', desc: 'La publicidad no es solo vender, es comunicar con intención.', manifesto: 'Creo conceptos publicitarios claros y creativos, enfocados en comunicar mensajes relevantes y conectar de manera auténtica.', services: ['Conceptualización de campañas', 'Dirección creativa', 'Storytelling visual', 'Comunicación estratégica'] },
    { id: 'marketing', icon: 'bar-chart-3', label: 'Marketing', role: 'Resultados Reales', desc: 'La creatividad también necesita estrategia.', manifesto: 'Trabajo estrategias creativas basadas en análisis, objetivos y público, buscando que cada acción tenga un propósito e impacto real.', services: ['Estrategia de marca', 'Marketing digital', 'Análisis creativo', 'Planeación de contenido'] }
];

export const projects = [
    { id: 1, title: 'Aura Branding', category: 'design', img: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=1000&auto=format&fit=crop', description: 'Sistema visual para marca de lujo.' },
    { id: 5, title: 'Zenit Studio', category: 'design', img: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=1000&auto=format&fit=crop', description: 'Papelería y manual de marca.' },
    { id: 2, title: 'Noches de Neón', category: 'illustration', img: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop', description: 'Serie de ilustraciones digitales experimentales.' },
    { id: 3, title: 'Impacto 2025', category: 'publicity', img: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?q=80&w=1000&auto=format&fit=crop', description: 'Campaña publicitaria disruptiva.' },
    { id: 4, title: 'Flujo de Datos', category: 'marketing', img: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1000&auto=format&fit=crop', description: 'Estrategia de crecimiento basada en datos.' },
    { id: 99, title: 'Protocolo Contacto', category: 'special', img: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80', description: '¿Tienes una idea, un proyecto o una marca que necesita dirección creativa? Estoy abierta a nuevas colaboraciones.' }
];
